name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push client image
      run: |
        docker build -t surya080903/ecotrack-client:latest -f ./client/Dockerfile ./client
        docker push surya080903/ecotrack-client:latest

    - name: Build and push server image
      run: |
        docker build -t surya080903/ecotrack-server:latest -f ./server/Dockerfile ./server
        docker push surya080903/ecotrack-server:latest

    - name: Install dependencies for Minikube
      run: |
        sudo apt-get update
        sudo apt-get install -y conntrack

    - name: Set up Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=none

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.0'

    - name: Create .kube directory and set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
        kubectl config use-context minikube

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ecotrack-deployment.yaml
        kubectl apply -f ecotrack-service.yaml
